export const FETCH_CARDS_REQUEST = "FETCH_CARDS_REQUEST";
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_ERROR = "FETCH_CARDS_ERROR";
export const CHANGE_ACTIVE_INDEX = "CHANGE_ACTIVE_INDEX";
export const FETCH_SITE_SUCCESS = "FETCH_SITE_SUCCESS"
export const FETCH_SITE_REQUEST = "FETCH_SITE_REQUEST";
export const FETCH_SITE_FAILURE = "FETCH_SITE_FAILURE";
export const RESET_ACTIVE_STATE = "RESET_ACTIVE_STATE"